name: Update cached versions

on:
  workflow_dispatch:
  schedule:
    - cron: '5 0 * * 5'

jobs:
  update_cache:
    runs-on: windows-latest
    env:
      HOME: D:/a/pyenv-win/pyenv-win
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Invoke update
      run: ${{ env.HOME }}/pyenv-win/bin/pyenv.bat update
      shell: bash
    - name: Push changes to origin
      run: |
        git config user.name github-actions
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add pyenv-win/.versions_cache.xml
        git commit -m 'chore: Update `.versions_cache.xml`'
        git push
